config/routes.rb
Rails.application.routes.draw do
  # Pages
  get '/', to: 'pages#root'
  get '/changelog', to: 'pages#changelog'

  # Autocomplete
  get '/items/autocomplete/:s', to: 'autocomplete#items'
  get '/mobs/autocomplete/:s', to: 'autocomplete#mobs'
  get '/maps/autocomplete/:s', to: 'autocomplete#maps'

  # Search
  get '/items/search', to: 'items#search'
  get '/mobs/search', to: 'mobs#search'
  get '/maps/search', to: 'maps#search'

  # Images
  get '/image/map/:name', to: 'images#map'
  get '/image/mob/:id', to: 'images#mob'
  get '/image/item/:id', to: 'images#item'
  get '/image/item_big/:id', to: 'images#item_big'

  # Resources
  resources :mobs, only: [:show]
  resources :items, only: [:show]
  resources :maps, only: [:show]
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :respawns

  def image
    "/image/map/#{name}.png"
  end

  def self.results_for(term)
    Map.where("lower(name) LIKE ?", "%#{term.downcase}%")
       .or(Map.where("lower(maps.desc) LIKE ?", "%#{term.downcase}%"))
       .or(Map.where("lower(sem_acento(maps.desc)) ILIKE ?", "%#{term.downcase}%"))
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @map = Map.find_by_name(params[:id])
  end

  def search
    @title = 'Busca de mapas'
    @maps = Map.results_for(params[:s]).limit(20)
    redirect_to map_path(@maps.first.name) if @maps.size == 1
  end
end

app/views/maps/search.html.erb
<div class="content-inside">

  <h1 class="title">Resultado da busca de mapas para "<%=params[:s]%>"</h1>
  <h2 class="subtitle">Foram encontrados <%=@maps.size%> mapas</h2>

  <% if @maps.any? %>
    <table class="table is-fullwidth is-striped">
      <% @maps.each do |map| %>
        <tr>
          <td>
            <a href="<%=map_path(map.name)%>"><%=map.desc%> (<%=map.name%>)</a>
          </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>Nada encontrado para sua busca.</p>
  <% end %>

</div>

app/views/maps/show.html.erb
<section class="hero">
  <div class="hero-body">
    <h1 class="title"><%= @map.desc %> (<%=@map.name%>)</h1>
    <!-- h2 com nome descritivo do mapa -->
  </div>
</section>
<div class="columns">
  <div class="column has-text-centered">
    <img id="map-image" data-src="<%=@map.image%>" />
  </div>
  <div class="column">
    <h4 class="title is-4">Respawns</h4>
    <% if @map.respawns.any? %>
      <table class="table is-fullwidth is-bordered is-hoverable">
        <tr>
          <th>Qtd</th>
          <th>Monstro</th>
          <th>Tempo</th>
        </tr>
        <% @map.respawns.each do |respawn| %>
          <% respawn_mob = Mob.find_by_id(respawn.mob_id) %>
          <tr>
            <td>
              <%=respawn.amount%>x
            </td>
            <td>
              <%= link_to respawn_mob.name, mob_path(respawn_mob.uid) %>
            </td>
            <td>
              <%=respawn.tempo%>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p>Este mapa não possui nenhum respawn</p>
    <% end %>
  </div>
</div>