config/routes.rb
Rails.application.routes.draw do
  # Pages
  get '/', to: 'pages#root'
  get '/changelog', to: 'pages#changelog'

  # Autocomplete
  get '/items/autocomplete/:s', to: 'autocomplete#items'
  get '/mobs/autocomplete/:s', to: 'autocomplete#mobs'
  get '/maps/autocomplete/:s', to: 'autocomplete#maps'

  # Search
  get '/items/search', to: 'items#search'
  get '/mobs/search', to: 'mobs#search'
  get '/maps/search', to: 'maps#search'

  # Images
  get '/image/map/:name', to: 'images#map'
  get '/image/mob/:id', to: 'images#mob'
  get '/image/item/:id', to: 'images#item'
  get '/image/item_big/:id', to: 'images#item_big'

  # Resources
  resources :mobs, only: [:show]
  resources :items, only: [:show]
  resources :maps, only: [:show]
end

app/models/mob.rb
class Mob < ApplicationRecord
  has_many :drops
  has_many :respawns
  has_one :mob_name

  def self.with_respawn
    Mob.includes(:respawns).where.not(respawns: { id: nil })
  end

  def size
    sizes = ['Pequeno', 'Médio', 'Grande']
    sizes[scale-1]
  end

  def image
    "/image/mob/#{uid}.gif"
  end

  def name
    mob_name.name_portuguese.blank? ? mob_name.name_english : mob_name.name_portuguese
  end

  def description
    "HP: #{hp} | Raça: #{race_text} | Tamanho: #{size} | Propriedade: #{element_text}"
  end

  def acerto
    level + agi + 20
  end

  def atk_delay
    "#{(adelay.to_f / 1000)}s"
  end

  def aspd
    delay = adelay.to_f / 1000
    hps = 1/delay
    (((200 * hps) - 50) / hps).to_i
  end

  def esquiva_95
     dex + level + 75
  end

  def real_base_exp
    return exp if Apartment::Tenant.current == 'public'
    site = Site.find_by_code(Apartment::Tenant.current)
    return exp * site.rate_exp
  end

  def real_job_exp
    return job_exp if Apartment::Tenant.current == 'public'
    site = Site.find_by_code(Apartment::Tenant.current)
    return job_exp * site.rate_base
  end

  def race_text
    races = ['Amorfo', 'Morto-Vivo', 'Bruto', 'Planta', 'Inseto', 'Peixe', 'Demônio', 'Humanóide', 'Anjo', 'Dragão',
            'Player']
    races[race]
  end

  def elemental_table
    file = File.open("#{Rails.root}/db/json/elements.json", "rb")
    contents = file.read
    objects = ActiveSupport::JSON.decode(contents)
    objects[element_text(true)]
  end

  def mode_text
    return search_for_mode(mode.to_i) if mode.to_i != 0
    modes = {
      '0x0081': 'Passivo',
      '0x0083': 'Passivo / Coletor',
      '0x1089': 'Passivo / Ajuda outros / Muda de Alvo / Corpo-a-corpo',
      '0x3885': 'Agressivo / Muda de Alvo / Corpo-a-corpo / Persegue',
      '0x2085': 'Agressivo / Muda de Alvo / Persegue',
      '0x0000': 'Passivo / Imóvel / Não ataca',
      '0x108B': 'Passivo / Coletor / Ajuda outros / Muda de Alvo / Corpo-acorpo',
      '0x7085': 'Agressivo / Muda de alvo / Persegue / Prefere alvos fracos',
      '0x3095': 'Agressivo / Muda de alvo / Corpo-a-corpo / Persegue / Detecta cast',
      '0x0084': 'Agressivo / Imóvel',
      '0x0084': 'Agressivo / Imóvel',
      '0x2085': 'Agressivo / Muda de Alvo / Persegue',
      '0x308D': 'Agressivo / Muda de Alvo / Corpo-a-corpo / Persegue / Ajuda outros',
      '0x0091': 'Passivo / Sensor de cast',
      '0x3095': 'Agressivo / Muda de Alvo / Corpo-a-corpo / Persegue / Detecta cast',
      '0x3295': 'Agressivo / Muda de Alvo / Corpo-a-corpo / Persegue / Detecta cast e persegue',
      '0x3695': 'Agressivo / Muda de Alvo / Corpo-a-corpo / Persegue / Detecta cast e persegue / Muda alvo da perseguição',
      '0x00A1': 'Passivo / Não anda aleatoriamente',
      '0x0001': 'Passivo / Não ataca',
      '0xB695': 'Agressivo / Muda de Alwo / Corpo-a-corpo / Persegue / Detecta cast / Alvo aleatório',
      '0x8084': 'Agressivo / Imóvel / Alvo aleatório',
    }

    return '' if mode.blank? || !modes.key?(mode.to_sym)
    return modes[mode.to_sym]
  end

  def element_text(slug = false)
    ret = ''
    elements_slug = ['neutral', 'water', 'earth', 'fire', 'wind', 'poison', 'holy', 'shadow', 'ghost', 'undead']
    elements = ['Neutro', 'Água', 'Terra', 'Fogo', 'Vento', 'Veneno', 'Sagrado', 'Sombrio', 'Fantasma', 'Maldito']
    levels = {
      '2': '1',
      '4': '2',
      '6': '3',
      '8': '4'
    }
    nivel = levels[:"#{element.to_s.split('').first}"]

    if slug
      ret += elements_slug[element.to_s.split('').last.to_i]
      ret += "_#{nivel}"
    else
      ret += elements[element.to_s.split('').last.to_i]
      ret += " nv. #{nivel}"
    end

  end

  def as_json(options={})
    super(options.merge({:methods => [:image, :name]}))
  end

  def self.results_for(term)

    mob_by_uid = Mob.where(uid: term).includes(:respawns)
    return mob_by_uid if mob_by_uid.any?

    mob_ids = MobName.where("lower(name_portuguese) LIKE ?", "%#{term.downcase}%")
                     .or(MobName.where("lower(name_english) LIKE ?", "%#{term.downcase}%"))
                     .or(MobName.where("lower(sem_acento(name_portuguese)) ILIKE ?", "%#{term.downcase}%"))
                     .pluck(:mob_id)
    Mob.with_respawn.includes(:respawns).where(id: mob_ids)
  end

  def boss_droper?
    is_mvp? || is_boss?
  end

  def is_mvp?
    search_for_mode(mode.to_i).split(', ').include?('MVP')
  end

  def is_boss?
    mob_mode = search_for_mode(mode.to_i).split(', ')
    ['Imune a status negativos', 'Não pode ser empurrado', 'Detecta em esconderijo'].all? do |status|
      mob_mode.include?(status)
    end
  end

  def search_for_mode(mode)
    modes = {
      'CAN_MOVE': 1,
      'Coletor': 2,
      'Agressivo': 4,
      'Ajuda outros': 8,
      'Detecta cast': 16,
      'Não anda aleatoriamente': 32,
      'Não utiliza habilidades': 64,
      'Ataca de volta': 128,
      '': 256,
      'Detecta cast e muda de alvo': 512,
      'Muda de alvo': 1024,
      'Irridadiço': 2048,
      'Muda de alvo ao ser atacado fisicamente': 4096,
      'Muda de alvo em perseguição': 8192,
      'Prefere alvos mais fracos': 16384,
      'Alvo aleatório': 32768,
      'Ignora atacantes físicos': 65536,
      'Ignora atacantes mágicos': 131072,
      'Ignora atacantes a distância': 262144,
      'MVP': 524288,
      'Toma apenas "1" de dano': 1048576,
      'Não pode ser empurrado': 2097152,
      '': 4194304,
      '': 8388608,
      'Drops não são afetados por consumíveis': 16777216,
      'Detecta em esconderijo': 33554432,
      'Imune a status negativos': 67108864,
      'Imune a habilidades': 134217728
    }

    modes = Hash[modes.to_a.reverse]
    mob_modes = get_modes(modes, mode).compact
    mob_modes.push('Não se move') unless mob_modes.include?(:CAN_MOVE)
    mob_modes.delete_if{ |i| i.blank? || i == :CAN_MOVE }.join(', ')
  end

  private

  def get_modes(_jobs, rema)
    _jobs.map do |key, value|
      if rema - value < 0
        _jobs.tap { |hs| hs.delete(key) }
        next
      end
      njobs = _jobs.clone
      njobs.tap { |hs| hs.delete(key) }
      ret = get_modes(njobs, rema - value)
      return [key] + ret
    end
  end

end

app/controllers/mobs_controller.rb
class MobsController < ApplicationController

  def show
    @mob = Mob.includes(:respawns, :drops).where(uid: params[:id]).where.not(respawns: { id: nil }).first
    raise ActiveRecord::RecordNotFound if @mob.blank?
    @title = @mob.name
    @image = @mob.image
    @description = @mob.description
  end

  def search
    @title = 'Busca de item'
    @mobs = Mob.results_for(params[:s]).limit(50)
    redirect_to mob_path(@mobs.first.uid) if @mobs.size == 1
  end
end

app/helpers/mobs_helper.rb
module MobsHelper
end

app/views/mobs/search.html.erb
<div class="content-inside">

  <h1 class="title">Resultado da busca de monstros para "<%=params[:s]%>"</h1>
  <h2 class="subtitle">Foram encontrados <%=@mobs.size%> monstros</h2>

  <% if @mobs.any? %>
    <table class="table is-fullwidth is-striped">
      <tr>
        <th colspan="2">Monstro</th>
        <th>Respawns</th>
      </tr>
      <% @mobs.each do |mob| %>
        <tr>
          <td width="80" class="has-text-centered">
            <img style="height:48px" src="<%=mob.image%>" />
          </td>
          <td style="padding-top:20px">
            <a href="<%=mob_path(mob.uid)%>"><%=mob.name%> (<%=mob.sprite%>)</a>
          </td>
          <td><%=mob.respawns.any? ? mob.respawns.includes(:map).map {|r| r.map.name }.join(', ') : 'Nenhum respawn' %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>Nada encontrado para sua busca.</p>
  <% end %>

</div>

app/views/mobs/show.html.erb
<section class="hero">
  <div class="hero-body no-left">
    <div class="container">
      <h1 class="title"><%=@mob.name%></h1>
      <h2 class="subtitle"><%=@mob.sprite%> (<%=@mob.uid%>)</h2>
    </div>
  </div>
</section>

<% table = @mob.elemental_table %>
<table class="table is-fullwidth is-bordered">
  <tr>
    <td rowspan="<%=@mob.is_boss? || @mob.is_mvp? ? '10' : '11' %>" colspan="4" align="center" valign="center" width="30%" class="has-text-centered" style="vertical-align:middle;">
      <img src="<%=@mob.image%>" style="padding-top:40px" />
    </td>
    <td colspan="2"><strong>Raça</strong></td>
    <td><%=@mob.race_text%></td>
    <td colspan="2"><strong>Elemento</strong></td>
    <td><%=@mob.element_text%></td>
    <td><strong>Propriedade</strong></td>
    <td><strong>Dano</strong></td>
  </tr>
  <tr>
    <td colspan="2"><strong>Nível</strong></td>
    <td><%=@mob.level%></td>
    <td colspan="2"><strong>Tamanho</strong></td>
    <td><%=@mob.size%></td>
    <td>Neutro</td>
    <td><%=format_element(table["neutral"])%></td>
  </tr>
  <tr>
    <td colspan="2"><strong>Alcance</strong></td>
    <td><%=@mob.range%> células</td>
    <td colspan="2"><strong>Ataque</strong></td>
    <td><%=@mob.atk1%> ~ <%=@mob.atk2%></td>
    <td>Água</td>
    <td><%=format_element(table["water"])%></td>
  </tr>
  <tr>
    <td colspan="2"><strong>HP</strong></td>
    <td><%=@mob.hp%></td>
    <td colspan="2"><strong>Defesa</strong></td>
    <td><%=@mob.def%></td>
    <td>Terra</td>
    <td><%=format_element(table["earth"])%></td>
  </tr>
  <tr>
    <td colspan="2"><strong>SP</strong></td>
    <td><%=@mob.sp%></td>
    <td colspan="2"><strong>Defesa Mágica</strong></td>
    <td><%=@mob.mdef%></td>
    <td>Fogo</td>
    <td><%=format_element(table["fire"])%></td>
  </tr>
  <tr>
    <td colspan="2"><strong>Experiência Base</strong></td>
    <td><%=@mob.real_base_exp%></td>
    <td colspan="2"><strong>Experiência de Classe</strong></td>
    <td><%=@mob.real_job_exp%></td>
    <td>Vento</td>
    <td><%=format_element(table["wind"])%></td>
  </tr>
  <tr>
    <td colspan="2"><strong>100% de Acerto</strong></td>
    <td><%=@mob.acerto%></td>
    <td colspan="2"><strong>95% de Esquiva</strong></td>
    <td><%=@mob.esquiva_95%></td>
    <td>Veneno</td>
    <td><%=format_element(table["poison"])%></td>
  </tr>
  <tr>
    <td colspan="2"><strong>Attack Delay</strong></td>
    <td><%=@mob.atk_delay%></td>
    <td colspan="2"><strong>ASPD</strong></td>
    <td><%=@mob.aspd%></td>
    <td>Sagrado</td>
    <td><%=format_element(table["holy"])%></td>
  </tr>
  <tr>
    <td><strong>FOR</strong></td>
    <td><strong>AGI</strong></td>
    <td><strong>VIT</strong></td>
    <td><strong>INT</strong></td>
    <td><strong>DES</strong></td>
    <td><strong>LUK</strong></td>
    <td>Sombrio</td>
    <td><%=format_element(table["shadow"])%></td>
  </tr>
  <tr>
    <td><%=@mob.str%></td>
    <td><%=@mob.agi%></td>
    <td><%=@mob.vit%></td>
    <td><%=@mob.int%></td>
    <td><%=@mob.dex%></td>
    <td><%=@mob.luk%></td>
    <td>Fantasma</td>
    <td><%=format_element(table["ghost"])%></td>
  </tr>
  <tr>
    <% if @mob.is_boss? || @mob.is_mvp? %>
      <td colspan="4" align="center" valign="center" class="has-text-centered" style="vertical-align:middle;">
        <img src="/mob_<%=@mob.is_mvp? ? 'mvp' : 'miniboss' %>.gif" />
      </td>
    <% end %>
    <td colspan="<%=@mob.is_boss? || @mob.is_mvp? ? '6' : '6' %>">
      <%=@mob.mode_text%>
    </td>
    <td>Maldito</td>
    <td><%=format_element(table["undead"])%></td>
  </tr>
</table>

<div class="columns">
  <div class="column content">
    <h4>Respawns</h4>
    <% if @mob.respawns.any? %>
      <table class="table is-striped is-bordered is-fullwidth">
        <tr>
          <th width="60">Quantidade</th>
          <th>Mapa</th>
          <th class="has-text-centered">Tempo</th>
        </tr>
        <% @mob.respawns.each do |respawn| %>
        <tr>
          <td class="has-text-centered"><%=respawn.amount%></td>
          <td><%= link_to respawn.respawn_map.name, map_path(respawn.respawn_map.name) %></td>
          <td class="has-text-centered"><%=respawn.tempo%></td>
        </tr>
        <% end %>
      </table>
    <% else %>
      <p>Este monstro não tem respawn em nenhum mapa</p>
    <% end %>
  </div>
  <div class="column content">
    <h4>Drops</h4>
    <% if @mob.drops.any? %>
      <table class="table is-striped is-bordered is-fullwidth">
        <tr>
          <th>Item</th>
          <th class="has-text-centered">Chance</th>
        </tr>
        <% @mob.drops.sort_by { |obj| obj.real_chance }.reverse.each do |drop| %>
          <tr>
            <td><a href="<%=item_path(drop.item.uid)%>">
              <img style="position: relative; top:4px" src="<%=drop.item.image%>" /> <%=drop.item.name %></a></td>
            <td class="has-text-centered"><%=drop.real_chance%>%</td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p>Este monstro não tem nenhum drop</p>
    <% end %>
  </div>
</div>